-- Generated by matugen
-- Do not edit manually

return {
	fg = "#1b1b21",
	fg_muted = "#45464f",

	bg = "#fbf8ff",
	bg_soft = "#edebf3",
	bg_high = "#e6e4eb",
	bg_highest = "#dedce4",

	primary = "#424e84",
	on_primary = "#ffffff",
	primary_container = "#98a4e0",
	on_primary_container = "#00062a",

	secondary = "#4d5064",
	on_secondary = "#ffffff",
	secondary_container = "#a3a6bd",

	tertiary = "#684761",
	on_tertiary = "#ffffff",
	tertiary_container = "#c39bb9",

	error = "#a6050f",
	on_error = "#ffffff",

	outline = "#6c6c75",
}
