$background = 130c0c
$onBackground = f9e0dd
$surface = 130c0c
$surfaceDim = 130c0c
$surfaceBright = 372927
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a1110
$surfaceContainer = 221716
$surfaceContainerHigh = 291d1c
$surfaceContainerHighest = 302221
$onSurface = f9e0dd
$surfaceVariant = 302221
$onSurfaceVariant = bca6a4
$outline = 84716f
$outlineVariant = 554443
$inverseSurface = fff8f7
$inverseOnSurface = 5d5352
$shadow = 000000
$scrim = 000000
$surfaceTint = f9b6b0
$primary = f9b6b0
$primaryDim = eaa9a3
$onPrimary = 613330
$primaryContainer = 764541
$onPrimaryContainer = ffdbd8
$inversePrimary = 85514d
$primaryFixed = ffbbb6
$primaryFixedDim = f0aea8
$onPrimaryFixed = 4e2421
$onPrimaryFixedVariant = 70403c
$secondary = e7bdb9
$secondaryDim = d8afab
$onSecondary = 563936
$secondaryContainer = 503432
$onSecondaryContainer = dfb6b2
$secondaryFixed = ffdad7
$secondaryFixedDim = f5cac6
$onSecondaryFixed = 553836
$onSecondaryFixedVariant = 745351
$tertiary = ffddb7
$tertiaryDim = fdcc91
$onTertiary = 6d4b1c
$tertiaryContainer = fdcc91
$onTertiaryContainer = 634215
$tertiaryFixed = fdcc91
$tertiaryFixedDim = eebe85
$onTertiaryFixed = 4e3003
$onTertiaryFixedVariant = 6e4b1d
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = a06864
$secondaryPaletteKeyColor = 916e6b
$tertiaryPaletteKeyColor = 97703e
$neutralPaletteKeyColor = 807473
$neutralVariantPaletteKeyColor = 867371
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = a06864
$secondary_paletteKeyColor = 916e6b
$tertiary_paletteKeyColor = 97703e
$neutral_paletteKeyColor = 807473
$neutral_variant_paletteKeyColor = 867371
$term0 = 353434
$term1 = ff5450
$term2 = ffbda3
$term3 = ffdfd7
$term4 = b9ab66
$term5 = f18f92
$term6 = ffba93
$term7 = f0d2ca
$term8 = b49e99
$term9 = ff857c
$term10 = ffd4c4
$term11 = fff1ee
$term12 = dcbc93
$term13 = ffa8a7
$term14 = ffd2bc
$term15 = ffffff
$rosewater = ffeeec
$flamingo = ffd9d6
$pink = ffd2d4
$mauve = ffa8b7
$red = ff9797
$maroon = f9aaa8
$peach = ffbeb3
$yellow = ffede9
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa1c2
$lavender = ffbacc
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5b6f
$kvisitedSelection = ce5b6f
$knegative = ec5351
$knegativeSelection = ec5351
$kneutral = ff8975
$kneutralSelection = ff8975
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f9e0dd
$subtext1 = bca6a4
$subtext0 = 84716f
$overlay2 = 746361
$overlay1 = 635352
$overlay0 = 534645
$surface2 = 443837
$surface1 = 352a2a
$surface0 = 241b1b
$base = 130c0c
$mantle = 130c0c
$crust = 120b0b
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
