-- Auto-generated by Matugen (Material You — transparent-friendly standalone template)
-- This file sets highlights directly (no base16 plugin required). It is safe to dofile().

-- Color palette placeholders (matugen will replace these)
local c = {
	-- base16-style slots (kept for compatibility)
	base00 = "#1a120e",
	base01 = "#140c09",
	base02 = "#221a15",
	base03 = "#52443d",
	base04 = "#d7c2b9",
	base05 = "#f0dfd8",
	base06 = "#382e2a",
	base07 = "#413732",

	base08 = "#ffb4ab",
	base09 = "#cfc890",
	base0A = "#e6beab",
	base0B = "#ffb691",
	base0C = "#4c481c",
	base0D = "#703716",
	base0E = "#5c4032",
	base0F = "#93000a",

	-- Material-You semantics (extra helpers if available)
	primary = "#ffb691",
	primary_container = "#703716",
	secondary = "#e6beab",
	tertiary = "#cfc890",
	on_surface = "#f0dfd8",
	on_tertiary_container = "#ece4aa",
	inverse_primary = "#8d4e2b",
}

-- Mark colorscheme name so Vim knows something is active
vim.g.colors_name = "matugen_materialyou"

-- Helper: safe hl setter
local function set_hl(group, attrs)
	pcall(vim.api.nvim_set_hl, 0, group, attrs)
end

local function set_hl_multiple(groups, attrs)
	for _, g in ipairs(groups) do
		set_hl(g, attrs)
	end
end

-- IMPORTANT:
-- To keep terminal transparency, we AVOID setting Normal.bg here.
-- If you prefer a solid background, set bg = c.base00 below.

-- Core UI (transparent-first: do NOT set Normal.bg)
set_hl("Normal", { fg = c.base05 }) -- keep bg unset for terminal transparency
set_hl("CursorLine", { bg = c.base01 }) -- subtle line highlight (if terminal opaque)
set_hl("LineNr", { fg = c.base03 })
set_hl("CursorLineNr", { fg = c.base05, bold = true })
set_hl("StatusLine", { bg = c.base01, fg = c.base05 })
set_hl("StatusLineNC", { bg = c.base00, fg = c.base03 })
set_hl("Pmenu", { bg = c.base01, fg = c.base05 })
set_hl("FloatBorder", { bg = c.base00, fg = c.base04 })
set_hl("NormalFloat", { bg = c.base00, fg = c.base05 })
set_hl("TabLine", { bg = c.base01, fg = c.base04 })
set_hl("TabLineSel", { bg = c.base02, fg = c.base05, bold = true })

-- Selection
-- Use a slightly tinted selection that still looks good on transparent terminals
set_hl("Visual", { bg = c.primary_container, fg = c.base00 })

-- Text / syntax (Material You leaning)
set_hl_multiple({ "Comment", "TSComment" }, { fg = c.on_tertiary_container, italic = true }) -- colored comments, readable on transparent bg
set_hl_multiple({ "Constant", "Number", "Boolean" }, { fg = c.base09 })
set_hl_multiple({ "Identifier", "TSVariable" }, { fg = c.base08 })
set_hl_multiple({ "Function", "TSFunction" }, { fg = c.base0B })
set_hl_multiple({ "Method", "TSMethod" }, { fg = c.base09 })
set_hl("Keyword", { fg = c.inverse_primary, bold = false })
set_hl("Statement", { fg = c.base0E })
set_hl("Conditional", { fg = c.base0E })
set_hl("Repeat", { fg = c.base0E })
set_hl("Operator", { fg = c.base0D })

-- UI messages
set_hl("MsgArea", { bg = c.base01, fg = c.base0B })

-- LSP / Diagnostics colors (clear and saturated for visibility on transparency)
set_hl("DiagnosticError", { fg = c.base08 })
set_hl("DiagnosticWarn", { fg = c.base0A })
set_hl("DiagnosticInfo", { fg = c.base0D })
set_hl("DiagnosticHint", { fg = c.base0C })

-- Treesitter / plugin niceties
set_hl_multiple({ "TSParameter", "TSProperty" }, { fg = c.base04 })
set_hl_multiple({ "TSType", "Type" }, { fg = c.base0A })
set_hl("CursorColumn", { bg = c.base01 })

-- make floating windows readable on transparent terminals
set_hl("NormalFloat", { bg = c.base00, fg = c.base05 })
set_hl("FloatBorder", { bg = c.base00, fg = c.base04 })

-- Optional: override some default highlights used by statuslines or plugins
set_hl("StatusLineTerm", { bg = c.base01, fg = c.primary })
set_hl("MatchParen", { fg = c.base0D, bg = c.base02, bold = true })

-- Return color table (optional)
return c
