# 暂停
SPACE cycle pause

# 退出 
q quit
ESC quit

# 调节音量，使用非标准组合键避免冲突
Shift+UP add volume 5
Shift+DOWN add volume -5

# 调节亮度
Ctrl+UP add brightness 0.1
Ctrl+DOWN add brightness -0.1

# 跳转到下一个视频
> playlist-next
# 跳转到上一个视频
< playlist-prev

# 截图
Shift+s screenshot

# 切换全屏，使用 F11 键
f cycle fullscreen
F11 cycle fullscreen
