# Shell variables
# Generated by 'wal'
wallpaper="/home/Nagisa/Pictures/Backgrounds/photo_2024-11-14_00-37-48.jpg"

# Special
background='#291b11'
foreground='#c9c6c3'
cursor='#c9c6c3'

# Colors
color0='#291b11'
color1='#CE3B21'
color2='#8D5F30'
color3='#8B6F4C'
color4='#768F33'
color5='#B3A657'
color6='#EAD59E'
color7='#c9c6c3'
color8='#766960'
color9='#CE3B21'
color10='#8D5F30'
color11='#8B6F4C'
color12='#768F33'
color13='#B3A657'
color14='#EAD59E'
color15='#c9c6c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
