--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Nagisa/Pictures/Backgrounds/photo_2024-11-14_00-37-48.jpg"

-- Special
background="#291b11"
foreground="#c9c6c3"
cursor="#c9c6c3"

-- Colors
color0="#291b11"
color1="#CE3B21"
color2="#8D5F30"
color3="#8B6F4C"
color4="#768F33"
color5="#B3A657"
color6="#EAD59E"
color7="#c9c6c3"
color8="#766960"
color9="#CE3B21"
color10="#8D5F30"
color11="#8B6F4C"
color12="#768F33"
color13="#B3A657"
color14="#EAD59E"
color15="#c9c6c3"
