[colors.primary]
background = "#291b11"
foreground = "#c9c6c3"

[colors.cursor]
text = "#291b11"
cursor = "#c9c6c3"

[colors.vi_mode_cursor]
text = "#291b11"
cursor = "#c9c6c3"

[colors.search.matches]
foreground = "#291b11"
background = "#c9c6c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#766960"
background = "#c9c6c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#291b11"
red = "#CE3B21"
green = "#8D5F30"
yellow = "#8B6F4C"
blue = "#768F33"
magenta = "#B3A657"
cyan = "#EAD59E"
white = "#c9c6c3"

[colors.bright]
black = "#766960"
red = "#CE3B21"
green = "#8D5F30"
yellow = "#8B6F4C"
blue = "#768F33"
magenta = "#B3A657"
cyan = "#EAD59E"
white = "#c9c6c3"

[colors.dim]
black = "#c9c6c3"
red = "#CE3B21"
green = "#B3A657"
yellow = "#8B6F4C"
blue = "#768F33"
magenta = "#8D5F30"
cyan = "#EAD59E"
white = "#766960"

