[colors]
background = '#291b118e'
black = '#291b11'
blue = '#CE3B21'
cursor = '#c9c6c3'
cyan = '#8D5F30'
foreground = '#c9c6c3'
green = '#8B6F4C'
magenta = '#768F33'
red = '#B3A657'
tabs = '#c9c6c3'
tabs-active = '#EAD59E'
white = '#c9c6c3'
yellow = '#c9c6c3'
dim-black = '#291b118e'
dim-blue = '#CE3B218e'
dim-cyan = '#8D5F308e'
dim-foreground = '#c9c6c38e'
dim-green = '#8B6F4C8e'
dim-magenta = '#768F338e'
dim-red = '#B3A6578e'
dim-white = '#EAD59E8e'
dim-yellow = '#c9c6c38e'
light-black = '#CE3B21'
light-blue = '#8D5F30'
light-cyan = '#8B6F4C'
light-foreground = '#768F33'
light-green = '#B3A657'
light-magenta = '#EAD59E'
light-red = '#c9c6c3'
light-white = '#CE3B21'
light-yellow = '#8D5F30'
