
$background = rgba(fbf8ffff)

$error = rgba(a6050fff)

$error_container = rgba(ff8376ff)

$inverse_on_surface = rgba(f2f0f7ff)

$inverse_primary = rgba(b8c3ffff)

$inverse_surface = rgba(303036ff)

$on_background = rgba(1b1b21ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(1f0000ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(00062aff)

$on_primary_fixed = rgba(ffffffff)

$on_primary_fixed_variant = rgba(ffffffff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(050819ff)

$on_secondary_fixed = rgba(ffffffff)

$on_secondary_fixed_variant = rgba(ffffffff)

$on_surface = rgba(1b1b21ff)

$on_surface_variant = rgba(45464fff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(170216ff)

$on_tertiary_fixed = rgba(ffffffff)

$on_tertiary_fixed_variant = rgba(ffffffff)

$outline = rgba(6c6c75ff)

$outline_variant = rgba(a7a6b0ff)

$primary = rgba(424e84ff)

$primary_container = rgba(98a4e0ff)

$primary_fixed = rgba(6571aaff)

$primary_fixed_dim = rgba(4d5990ff)

$scrim = rgba(000000ff)

$secondary = rgba(4d5064ff)

$secondary_container = rgba(a3a6bdff)

$secondary_fixed = rgba(707389ff)

$secondary_fixed_dim = rgba(585b6fff)

$shadow = rgba(000000ff)

$source_color = rgba(063ac4ff)

$surface = rgba(fbf8ffff)

$surface_bright = rgba(fbf8ffff)

$surface_container = rgba(edebf3ff)

$surface_container_high = rgba(e6e4ebff)

$surface_container_highest = rgba(dedce4ff)

$surface_container_low = rgba(f5f2faff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d5d3dbff)

$surface_tint = rgba(4f5b92ff)

$surface_variant = rgba(e2e1ecff)

$tertiary = rgba(684761ff)

$tertiary_container = rgba(c39bb9ff)

$tertiary_fixed = rgba(8d6985ff)

$tertiary_fixed_dim = rgba(73516cff)


