-- Auto-generated by Matugen (Material You — Enhanced Semantics)
-- Save this file to ~/.config/matugen/templates/nvim-material-you.lua

local c = {
	-- 基础背景与前景 (用于 UI)
	-- 注意：Matugen 的 background 通常很深，surface 稍亮
	bg_default = "{{colors.background.default.hex}}",
	fg_default = "{{colors.on_surface.default.hex}}", -- 主要文字
	fg_subtle = "{{colors.on_surface_variant.default.hex}}", -- 次要文字
	fg_muted = "{{colors.outline.default.hex}}", -- 这里的 outline 是最适合做注释的灰色

	-- 界面容器 (用于行号栏、状态栏)
	surface = "{{colors.surface.default.hex}}",
	surface_dim = "{{colors.surface_container_low.default.hex}}",
	surface_bright = "{{colors.surface_container_high.default.hex}}",

	-- 选区颜色 (Material You 标准)
	selection_bg = "{{colors.primary_container.default.hex}}",
	selection_fg = "{{colors.on_primary_container.default.hex}}",

	-- 核心强调色 (用于代码高亮)
	primary = "{{colors.primary.default.hex}}", -- 对应函数/方法
	secondary = "{{colors.secondary.default.hex}}", -- 对应字符串/类型
	tertiary = "{{colors.tertiary.default.hex}}", -- 对应关键字/控制流
	error = "{{colors.error.default.hex}}",

	-- 特殊语义
	diff_add = "{{colors.green.default.hex}}", -- 如果没有 green 这种硬编码，可以用 tertiary_container
	diff_change = "{{colors.primary_container.default.hex}}",
	diff_delete = "{{colors.error_container.default.hex}}",
}

vim.g.colors_name = "matugen_materialyou_v2"

local function set_hl(group, attrs)
	pcall(vim.api.nvim_set_hl, 0, group, attrs)
end

local function set_hl_multiple(groups, attrs)
	for _, g in ipairs(groups) do
		set_hl(g, attrs)
	end
end

-- =========================================================
--  UI 基础设置 (保留透明支持)
-- =========================================================

-- Normal: 不设置 bg 以保持终端透明。如果你想要不透明，加上 bg = c.bg_default
set_hl("Normal", { fg = c.fg_default })

-- 行号与光标行
set_hl("LineNr", { fg = c.fg_muted }) -- 灰色的行号
set_hl("CursorLineNr", { fg = c.primary, bold = true }) -- 当前行号高亮为主色
set_hl("CursorLine", { bg = c.surface_dim }) -- 极淡的当前行背景

-- 状态栏与分割线
set_hl("StatusLine", { bg = c.surface, fg = c.fg_default })
set_hl("StatusLineNC", { bg = c.bg_default, fg = c.fg_muted })
set_hl("WinSeparator", { fg = c.fg_muted }) -- 分割线使用灰色

-- 浮动窗口 (Pmenu)
set_hl("NormalFloat", { bg = c.surface, fg = c.fg_default }) -- 浮动窗不透明，保证可读性
set_hl("FloatBorder", { bg = c.surface, fg = c.fg_muted })
set_hl("Pmenu", { bg = c.surface, fg = c.fg_default })
set_hl("PmenuSel", { bg = c.selection_bg, fg = c.selection_fg, bold = true })

-- 搜索与选区
set_hl("Visual", { bg = c.selection_bg, fg = c.selection_fg })
set_hl("Search", { bg = c.tertiary, fg = c.bg_default })
set_hl("IncSearch", { bg = c.primary, fg = c.bg_default })

-- =========================================================
--  代码语法高亮 (Material You 风格)
-- =========================================================

-- 1. 注释：绝对的灰色 (使用 outline 颜色)
set_hl("Comment", { fg = c.fg_muted, italic = true })
set_hl("TSComment", { link = "Comment" })

-- 2. 关键字：使用 Tertiary (通常是暖色或与主色对比的颜色)
--    这包括 if, else, for, return 等
set_hl_multiple(
	{ "Keyword", "Statement", "Conditional", "Repeat", "Label", "Operator" },
	{ fg = c.tertiary, bold = true }
)

-- 3. 函数与方法：使用 Primary (主色)
--    这是代码里的核心动作，用主色强调
set_hl_multiple({ "Function", "Method", "TSFunction", "TSMethod" }, { fg = c.primary, bold = true })

-- 4. 字符串与常量：使用 Secondary (次要色)
--    Material Design 中 Secondary 常用于补充信息，适合字符串
set_hl_multiple({ "String", "Character", "Constant", "Number", "Boolean", "Float" }, { fg = c.secondary })

-- 5. 类型与类：使用 Secondary 或 Tertiary
set_hl_multiple({ "Type", "Structure", "StorageClass", "TSType", "TSConstructor" }, { fg = c.secondary, italic = true })

-- 6. 变量与标识符：保持默认前景色 (fg_default) 或者稍微淡一点
--    让变量名为白色/默认色，可以反衬出彩色的关键字和函数，避免“圣诞树”效应
set_hl_multiple({ "Identifier", "TSVariable", "TSParameter" }, { fg = c.fg_default })
--    (可选) 如果你希望变量也是彩色的，可以取消下面这行的注释并改用 c.fg_subtle
--    set_hl("TSVariable", { fg = c.fg_subtle })

-- 7. 错误与特殊符号
set_hl("Special", { fg = c.tertiary }) -- 正则表达式等
set_hl("Error", { fg = c.error })
set_hl("Todo", { fg = c.bg_default, bg = c.primary, bold = true }) -- TODO 标签高亮

-- =========================================================
--  插件与特定 UI
-- =========================================================

-- Diagnostics (LSP 诊断)
set_hl("DiagnosticError", { fg = c.error })
set_hl("DiagnosticWarn", { fg = c.tertiary })
set_hl("DiagnosticInfo", { fg = c.secondary })
set_hl("DiagnosticHint", { fg = c.fg_muted })

-- Gitsigns / Diff
set_hl("DiffAdd", { fg = c.diff_add })
set_hl("DiffChange", { fg = c.diff_change })
set_hl("DiffDelete", { fg = c.diff_delete })

return c
