
$background = rgba(f9f9ffff)

$error = rgba(a6050fff)

$error_container = rgba(ff8376ff)

$inverse_on_surface = rgba(f0f0f7ff)

$inverse_primary = rgba(a8c8ffff)

$inverse_surface = rgba(2e3035ff)

$on_background = rgba(191c20ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(1f0000ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(00091cff)

$on_primary_fixed = rgba(ffffffff)

$on_primary_fixed_variant = rgba(ffffffff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(020a18ff)

$on_secondary_fixed = rgba(ffffffff)

$on_secondary_fixed_variant = rgba(ffffffff)

$on_surface = rgba(191c20ff)

$on_surface_variant = rgba(43474eff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(14031cff)

$on_tertiary_fixed = rgba(ffffffff)

$on_tertiary_fixed_variant = rgba(ffffffff)

$outline = rgba(6a6d75ff)

$outline_variant = rgba(a4a7b0ff)

$primary = rgba(315282ff)

$primary_container = rgba(88a8deff)

$primary_fixed = rgba(5575a8ff)

$primary_fixed_dim = rgba(3c5d8eff)

$scrim = rgba(000000ff)

$secondary = rgba(485263ff)

$secondary_container = rgba(9ea8bcff)

$secondary_fixed = rgba(6b7588ff)

$secondary_fixed_dim = rgba(535c6eff)

$shadow = rgba(000000ff)

$source_color = rgba(0d72d5ff)

$surface = rgba(f9f9ffff)

$surface_bright = rgba(f9f9ffff)

$surface_container = rgba(ebecf2ff)

$surface_container_high = rgba(e4e4ebff)

$surface_container_highest = rgba(dcdde4ff)

$surface_container_low = rgba(f3f3faff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d3d4daff)

$surface_tint = rgba(3e5f90ff)

$surface_variant = rgba(e0e2ecff)

$tertiary = rgba(614968ff)

$tertiary_container = rgba(bb9ec1ff)

$tertiary_fixed = rgba(866c8dff)

$tertiary_fixed_dim = rgba(6c5373ff)


